services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "${RTMP_PORT}:1935"
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx-rtmp/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-rtmp/data/hls/dashcam:/data/hls/dashcam
      - ./nginx-rtmp/data/hls/live:/data/hls/live
      - ./nginx-rtmp/data/recordings:/data/recordings
    restart: unless-stopped

  live-record:
    build:
      context: ./live-record
    volumes:
      - ./nginx-rtmp/data/recordings:/data/recordings
      - ./live-record/convert.sh:/convert.sh
    restart: unless-stopped
    entrypoint: sh -c 'chmod +x /convert.sh && /convert.sh'

  dashcam-record:
    build:
      context: ./dashcam-record
    volumes:
      - ./nginx-rtmp/data/recordings:/data/recordings
      - ./nginx-rtmp/data/hls/dashcam:/data/hls/dashcam:ro
      - ./dashcam-record/watch.sh:/watch.sh
    restart: unless-stopped
    entrypoint: sh -c 'chmod +x /watch.sh && /watch.sh'

  dashcam-record-notify:
    image: oven/bun:1
    user: bun
    working_dir: /app
    volumes:
      - ./dashcam-record-notify:/app
      - ./nginx-rtmp/data/recordings/dashcam:/data/recordings/dashcam:ro
    restart: unless-stopped
    entrypoint: sh -c 'bun install && bun run start'

  websocket:
    build:
      context: ./websocket
    restart: unless-stopped
    ports:
      - '${WEBSOCKET_PORT}:3000'
    working_dir: /app
    volumes:
      - ./websocket:/app
    entrypoint: sh -c 'bun install && bun run start'

