services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "${RTMP_PORT}:1935"
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx-rtmp/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-rtmp/data/hls/cam:/data/hls/cam
      - ./nginx-rtmp/data/hls/live:/data/hls/live
      - ./nginx-rtmp/data/recordings:/data/recordings
    restart: unless-stopped

  ffmpeg-converter:
    build:
      context: ./ffmpeg-converter
      dockerfile: Dockerfile
    volumes:
      - ./nginx-rtmp/data/recordings:/data/recordings
      - ./ffmpeg-converter/watch-and-convert.sh:/watch-and-convert.sh
    restart: unless-stopped
    entrypoint: sh -c 'chmod +x /watch-and-convert.sh && /watch-and-convert.sh'

  websocket:
    build:
      context: ./websocket
    restart: unless-stopped
    ports:
      - '${WEBSOCKET_PORT}:3000'
    working_dir: /app
    volumes:
      - ./websocket:/app
    entrypoint: sh -c 'bun install && bun run start'

